//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrailerModCreator.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TrailerModCreator.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to trailer : trailer.&lt;intname&gt; 
        ///{
        ///	accessories[]: .&lt;intname&gt;.tchassis
        ///	#addwheel
        ///	#addcargo
        ///	#addpaint
        ///}
        ///
        ///vehicle_accessory: .&lt;intname&gt;.tchassis
        ///{
        ///    	data_path: &quot;/def/vehicle/trailer/&lt;trailer&gt;.sii&quot;
        ///}
        ///
        ///#addwheeldef 
        ///
        ///#addpaintdef
        ///#addcargodef
        ///.
        /// </summary>
        internal static string blankSii {
            get {
                return ResourceManager.GetString("blankSii", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to car_transporter/cargo_octavia.sii,car transporter cargo octavia 
        ///car_transporter/cargo_octavia_2.sii,car transporter cargo octavia 2 
        ///car_transporter/cargo_octavia_3.sii,car transporter cargo octavia 3 
        ///cement_mixer/mixer.sii,cement mixer mixer 
        ///overweight/twocats.sii,overweight twocats 
        ///overweight/catg.sii,overweight catg 
        ///overweight/cat422.sii,overweight cat422 
        ///overweight/excavator.sii,overweight excavator 
        ///flat_bed/empty_tank.sii,flat bed empty tank 
        ///flat_bed/hi_pressure_tank.sii,flat bed hi pr [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string defCargo {
            get {
                return ResourceManager.GetString("defCargo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to aero_dynamic/chassis.sii,aero dynamic,3,1 
        ///brick_trailer/chassis_explo.sii,brick trailer explo,3,0
        ///brick_trailer/chassis.sii,brick trailer,3,0
        ///car_transporter/chassis.sii,car transporter,3,0
        ///car_transporter/chassis_blue.sii,car transporter blue,3,0
        ///car_transporter/chassis_black.sii,car transporter black,3,0
        ///cement/chassis.sii,cement,3,1
        ///cement_mixer/chassis.sii,cement mixer,3,0
        ///chemical_cistern/chassis.sii,chemical cistern,3,1
        ///container/chassis.sii,container,3,1
        ///overweight/chassis.sii,overweight,3 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string defChassis {
            get {
                return ResourceManager.GetString("defChassis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to aero_dynamic,aero_dynamic 
        ///brick_explo,brick.explo.trailer
        ///brick_trailer,brk_trailer 
        ///car_transporter,car_trans 
        ///car_transporter_2,car_trans2 
        ///car_transporter_3,car_trans3 
        ///cement,cement 
        ///cement_mixer,cement_mix 
        ///chemical_cistern,chcistern 
        ///container,container 
        ///digger,overweight.digger 
        ///digger1000,overweight.digger1000 
        ///digger500,overweight.digger500 
        ///excavator,overweight.excavator 
        ///flat_bed_empty_tank,flat_bed.empty_tank 
        ///flat_bed_hi_press_tank,flat_bed.hipress_tank 
        ///flat_bed_over_cargo,fla [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string defTrailers {
            get {
                return ResourceManager.GetString("defTrailers", resourceCulture);
            }
        }
    }
}
